### ISSUE TITLE
Uncaught ReferenceError: Chromestore is not defined 

### ISSUE THREAD

**Issue by Jones-S** [summera/chromestore.js#2]
Hi there

I have cloned your repo here and I finally want to use it to write some data into a json file.
unfortunately I cannot initiate chromestore from the beginning.
When I run your chromestore-test it seems to work fine, although I cannot find any files on my harddrive... (are there some created anyway?)

Well I get this error:
```
Uncaught ReferenceError: Chromestore is not defined 
```

First I thought I did not load your chromestore.js or i loaded it accidentally before my own js file.
But thats not the case.
I also think I'm waiting long enough to load everything else...
I use this code in my js file:

```javascript
$(document).ready(function() {

    //initiate chromestore
    var cs = new Chromestore([{
        path: 'export/exportJSON',
        callback: function() {
            console.log('finished creating export folder tree')
        }
    }]);

    //request bytes from filesystem
    cs.init(1024 * 1024, function(cstore) {
        console.log('Chromestore initialized');
    });

    //create file
    cs.getFile('export/exportJSON/fileCreate.txt', {
        create: true,
        exclusive: true
    }, function(fileEntry) {
        console.log('File created');
    });


});

```

and my html looks like this:

```html

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<script type="text/javascript" src="../../03_libs/jquery/jquery-2.1.1.js"></script>
	<script type="text/javascript" src="chromestorejs/chromestore.js"></script>
	<script type="text/javascript" src="csvjson.js"></script>
</head>
<body>


</body>
</html>

```

Do you have a clue, why chromestore does seem to be there already?
Thanks, help would be very appreciated...

**Comment by alexey-shaposhnikov** [comment]
```
cs = new ChromeStore()
```
works fine for me

**Comment by summera** [comment]
@Jones-S if you are still having issues, let me know
