### ISSUE TITLE
Reading content of a previously stored text (JSON) file.

### ISSUE THREAD

**Issue by alexKleider** [summera/chromestore.js#7]
Once data (in my use case: JSON text) is stored by chromestore.js on the local (client) machine, what is the mechanism of subsequently reading it for further use by local javascript routines? TIA Alex

**Comment by summera** [comment]
Hey Alex!

chromestore.js [getFile](http://usa.yamaha.com/products/music-production/speakers/hs_series/?mode=series) method returns a [FileEntry](https://developer.mozilla.org/en-US/docs/Web/API/FileEntry) object to the callback. `FileEntry` represents a file in a filesystem. Once you receive the `FileEntry` you can then read it using a `FileReader`. For example:

``` javascript
cs.getFile('myfile.json', {}, function(fileEntry) {
    fileEntry.file(function(file) {
       var reader = new FileReader();

       reader.onloadend = function(e) {
         // do something with data here
         var myData = this.result; 
       };

       reader.readAsText(file);
    }, errorHandler);
})
```

This is also how file writing is handled, however chromestore.js abstracts away some of these details by creating its own [FileWriter](https://github.com/summera/chromestore.js/blob/master/chromestore.js#L396) object when you call the [write](https://github.com/summera/chromestore.js/blob/master/chromestore.js#L290) method. We could do the same for FileReader, but at the time of making it was not needed. If you'd like to take a stab at it you are certainly welcome to! 

http://www.html5rocks.com/en/tutorials/file/filesystem/ is great for learning about the filesystem API. Let me know if you have any issues/questions with this.
